### ISSUE TITLE
There is a problem in the compilation process

### ISSUE THREAD

**Issue by sly-97** [steveazzolin/RGExplainer_new#1]
input_lin = self.embedding(x, edge_index, edge_weights)
    out1 = self.conv1(x, edge_index, edge_weights)
  File "/Users/air/miniforge3/envs/tf26/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/air/miniforge3/envs/tf26/lib/python3.10/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 242, in forward
    edge_index, edge_weight, x.size(self.node_dim),
TypeError: 'int' object is not callable

I have changed it many times, but this problem has not been solved. I would like to ask if you have any solutions here

Another problem is the lack of model files here.
FileNotFoundError: [Errno 2] No such file or directory: '../Explaining-the-Explainers-in-Graph-Neural-Networks/models/ba_2grid_cheb'

**Comment by steveazzolin** [comment]
Hi,

This is a personal fork that was modified for my personal needs.
I suggest checking out the original repo.

Best,
Steve

**Comment by abstinence277** [comment]
Hi,

I couldn't find the origin repo. Could you share the link here?

Best

**Comment by steveazzolin** [comment]
You can find the code on the Openreview page of the paper:
https://openreview.net/forum?id=nUtLCcV24hL

I'll update the Readme accordingly.

Best
